config/routes.rb
Rails.application.routes.draw do

  resources :cards
  resources :videos, only: [:index, :show, :create, :destroy]
  get "/info" => "info#index"

  get "/:id" => "cards#show_by_slug", as: 'cardslug'

  root 'cards#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
  has_many :videos, dependent: :destroy
  has_many :invitations

  validates :slug, presence:true, uniqueness: true
  validates :title, presence: true
  validates :email, presence: true
  validates :category, presence: true

  before_create :generate_auth_token

  CARD_CATEGORIES = ['birthday', 'congratulations', 'wedding', 'anniversary', 'sympathy', 'thank_you', 'generic']

  def to_param
    # instead of id
    auth_token
  end


  def generate_auth_token
    # in a world where millions of people will use this, we would 
    # check to make sure the token is not duplicated.  We are not in that world.
    self.auth_token = SecureRandom.hex
  end


end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :card
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :card

  validates :video_uuid, presence: true
  # scope :complete, { where(:completed => true) }

  before_create :generate_auth_token

  CARD_CATEGORIES = ['birthday', 'congratulations', 'wedding', 'anniversary', 'sympathy', 'thank_you', 'generic']


  def generate_auth_token
    # in a world where millions of people will use this, we would 
    # check to make sure the token is not duplicated.  We are not in that world.
    self.auth_token = SecureRandom.hex
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]


  def index
    @card = Card.new
  end

  # GET /cards/1
  # GET /cards/1.json

  def show_by_slug
    @card = Card.find_by_slug(params[:id])
    @video = Video.new
    if @card
      render 'show'
    else
      redirect_to new_card_path
    end
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  def show
    @video = Video.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    if @card.save
      UserMailer.welcome_email(@card).deliver_later
      redirect_to cardslug_path(@card.slug)
    else
      render 'new'
    end
  end

  def update
    if @card.update(card_params) 
      flash.now[:notice] = 'Card was successfully updated.'
    else
      flash.now[:error] = 'Card was not updated.'
    end
    render 'edit'
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    #@card.destroy
    redirect_to root_path, notice: 'Card was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      #the id passed in will be an auth_token, not a simple id
      @card = Card.find_by_auth_token(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
    params.require(:card).permit(:slug, :title, :category, :email)
    end
  
end

app/controllers/info_controller.rb
class InfoController < ApplicationController

  def index
  	@card = Card.new
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  
  def create
  	@card = Card.find(video_params[:card_id])

  	@video = Video.new(video_params)

        # going straight to the params hash because camera tag nests it within weird subhashes
        @video.thumb = params[:video][:qvga][:thumb]
        @video.small_thumb = params[:video][:qvga][:small_thumb]

  	@video.save
        redirect_to cardslug_path(@card.slug)
  end

  def show
    @video = Video.find_by_auth_token(params[:id])
  end


  def destroy
    @video = Video.find_by_auth_token(params[:id])
    card = @video.card
#    @video.destroy

    # get some info about the calling controller / method
    source_page = Rails.application.routes.recognize_path(request.referrer)

    if source_page[:controller] == 'videos'
      redirect_to cardslug_path(card.slug), notice: 'Video was successfully destroyed.' 
    else
      # this means the destroy request came from the edit card page
      redirect_to :back, notice: 'Video was successfully destroyed.' 
    end
  end

  def video_params
  	params.require(:video).permit(:contributor, :card_id, :video_uuid)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end



end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/cards/edit.html.erb
<h3>Edit your Cluster Card</h3>

<%= flash_messages %>

<%= bootstrap_form_for @card do |f| %>
  <h3>Your card can be viewed at</h3>
  <%= link_to "http://clustercard.net/#{@card.slug}", cardslug_path(@card.slug) %>

  <%= f.text_field :title %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= button_to "Delete this card", card_path(:id => @card.auth_token), :method => :delete, :class => 'btn btn-large btn-warning', data: { confirm: 'Are you sure?'} %>



<h3>Card Videos</h3>

<% @card.videos.each do |v| %>

  <video id='vid_<%=v.id%>' data-uuid='<%= v.video_uuid %>'></video><br> 
  <%= button_to "Delete this video", video_path(:id => v.auth_token), :method => :delete, :class => 'btn btn-large btn-warning', data: { confirm: 'Are you sure?'} %>


<% end %>

app/views/cards/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<!-- <div class="page-header">
    <center><h1 id="container"></h1></center>
    <div
  		class="fb-like"
  		data-share="true"
  		data-width="450"
  		data-show-faces="true">
	</div>
</div> -->

<section id="hero" class="anniversary">
  <div class="overlay">
    <div class="container">
      <h1 class="text-center">Cluster Card</h1>
      <div class="row">
        <div class="col-md-6 col-md-offset-3 text-center">
          <p class="lead">Crowdsourced video greeting cards<br class="hidden-sm"> for family, friends -- or anyone!</p>
        </div>
      </div>
      
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <div class="row text-center">
            <div class="col-md-4">
              <p>Create a card with a unique web address.</p>
            </div>
            <div class="col-md-4">
              <p>Upload a video and<br>attach it to a card.</p>
            </div>
            <div class="col-md-4">
              <p>Invite more contributors!</p>
            </div>
          </div>
        </div>
      </div>
      <br>
      <div class="text-center">
        <p>Easy. &nbsp;Fast.<br>Right from your phone or browser.</p>
      </div>
        
        <div class="row cta">
          <div class="col-md-12 text-center">
            <%= link_to 'Get Started Now', new_card_path, class: "btn btn-primary btn-xl" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="examples">
  <div class="container">
    <h2 class="text-center">Card Categories</h2>

    <div class="row">
      <div class="col-md-4">
        <div class="card birthday">
          <div class="overlay">
            <div class="frame">
              <h3><%= "#{Card::CARD_CATEGORIES[0]}" %></h3>
              <p>Don't send the same ol' FB post!  Send your friends or loved ones a video ClusterCard to wish a very <i>Happy Birthday!</i></p>

              <hr>
              <div class="text-center clearfix actions">
              <%= link_to 'See Example', cardslug_path('birthday'), class: "btn btn-default pull-left", method: :get %> OR <%= link_to 'Create your own', cards_path, class: "btn btn-primary pull-right", method: :get %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card congratulations">
          <div class="overlay">
            <div class="frame">
              <h3><%= "#{Card::CARD_CATEGORIES[1]}" %></h3>
              <p>New family addition?  New graduate?  New job?  Send your 'Congrats' with a video ClusterCard!</p>
              <hr>
              <div class="text-center clearfix actions">
                <%= link_to 'See Example', cardslug_path('congratulations'), class: "btn btn-default pull-left", method: :get %> OR <%= link_to 'Create your own', cards_path, class: "btn btn-primary pull-right", method: :get %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card wedding">
          <div class="overlay">
            <div class="frame">
              <h3><%= "#{Card::CARD_CATEGORIES[2]}" %></h3>
              <p>Send some heart-felt wishes for this special occasion.</p>
              <hr>
              <div class="text-center clearfix actions">
              <%= link_to 'See Example', cardslug_path('wedding'), class: "btn btn-default pull-left", method: :get %> OR <%= link_to 'Create your own', cards_path, class: "btn btn-primary pull-right", method: :get %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <div class="card anniversary">
          <div class="overlay">
            <div class="frame">
              <h3><%= "#{Card::CARD_CATEGORIES[3]}" %></h3>
              <p>Share the love with anniversary wishes to the deserving couple.</p>
              <hr>
              <div class="text-center clearfix actions">
              <%= link_to 'See Example', cardslug_path('anniversary'), class: "btn btn-default pull-left" %> OR <%= link_to 'Create your own', cards_path, class: "btn btn-primary pull-right", method: :get %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card sympathy">
          <div class="overlay">
            <div class="frame">
              <h3><%= "#{Card::CARD_CATEGORIES[4]}" %></h3>
              <p>Say <i>I'm here for you</i> with a simple, meaningful video message.</p>
              <hr>
              <div class="text-center clearfix actions">
              <%= link_to 'See Example', cardslug_path('sympathy'), class: "btn btn-default pull-left", method: :get %> OR <%= link_to 'Create your own', cards_path, class: "btn btn-primary pull-right", method: :get %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card thank_you">
          <div class="overlay">
            <div class="frame">
              <h3><%= "#{Card::CARD_CATEGORIES[5]}" %></h3>
              <p>Your <i>THANK YOU</i> can mean so much more when you say it with a ClusterCard! </p>
              <hr>
              <div class="text-center clearfix actions">
              <%= link_to 'See Example', cardslug_path('thanks'), class: "btn btn-default pull-left", method: :get %> OR <%= link_to 'Create your own', cards_path, class: "btn btn-primary pull-right", method: :get %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row text-center">
        <p>Don't see a Category to fit your video card?</p>
        <p>No problem!</p>
        <p>Create your own fun ClusterCard!</p>
      </div>

    <div class="row cta">
      <div class="col-md-12 text-center">
        <%= link_to 'Create Your Card', new_card_path, class: "btn btn-primary btn-xl" %>
      </div>
    </div>
  </div>
</section>

app/views/cards/new.html.erb
<script>
  $(function() {
  $(".bs-wizard").bs_wizard();
  });
</script>

<div class="container">
  <div class="row bs-wizard">
    <div class="col-md-6 col-md-offset-3">
      <div class="well bs-component">
        <%= bootstrap_form_for(@card) do |f| %>

          <div class="bs-step inv">
            <div class="bs-step-inner">
              <h3 class="text-center">What URL would you like for your card?</h3>
                <div class="input-group">
                  <span class="input-group-addon" id="basic-addon1">http://clustercard.net/</span>
                  <%= f.text_field :slug, hide_label: true, :required => "true", :class => 'input-lg' %>
                </div>
            </div>
          </div>

          <div class="bs-step inv">
            <div class="bs-step-inner">
              <h3 class="text-center">What title would you like for your card?</h3>
              <%= f.text_field :title, hide_label: true, placeholder: 'e.g. "Happy 78th to Uncle Bob!"', :class => 'input-lg' %>
            </div>
          </div>

          <div class="bs-step inv">
            <div id="selectTheme" class="bs-step-inner">
              <h3 class="text-center">Pick a theme for your card:</h3>
              <%= f.form_group :category do %>
                <% Card::CARD_CATEGORIES.each do |cc| %>
                  <% if cc == "birthday" %>
                    <%= f.radio_button :category, cc, label: cc.humanize, checked: true %>
                  <% else %>
                    <%= f.radio_button :category, cc, label: cc.humanize %>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>

          <div class="bs-step inv">
            <div class="bs-step-inner">
              <h3 class="text-center">Enter your email so we can send you a link to edit this card:</h3>
              <%= f.text_field :email, hide_label: true, placeholder: 'somebody@example.com', :class => 'input-lg' %>
              <%= f.submit "Go To Your Card", class: "btn btn-primary btn-lg btn-block" %>
            </div>
          </div>

              </section>
            </div>
          </div>
        <% end %>
      
      </div>
    </div>
  </div>
</div>

app/views/cards/oldnew.html.erb
<div class="row">
    <div class="col-lg-6">
        <div class="well bs-component">
            <center><legend><h1>Add a Title to Your Card:</h1></legend>
              <h3>A sample title might be "Happy 50th Uncle Mike!" </h3>
            <div class="col-lg-10">
                <%= bootstrap_form_for(@card, layout: :inline) do |f| %>
                    <h2><%= f.hidden_field :slug, value: @card.slug %>
                    <%= f.label :title, 'Title: ' %>
                    <%= f.text_field :title, hide_label: true, required: true %><br><br>
                    <p><%= f.submit "Add to Card", class: "btn btn-primary btn-block" %></p></center>
                <% end %>
                    <%= link_to 'Back', root_path %></h2>
            </div>
        </div>
    </div>
</div>

app/views/cards/show.html.erb
<div class="showcardcontainer <%=@card.category %>">
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '2051596044981118',
      xfbml      : true,
      version    : 'v2.3'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>




<script>
  var cluster_camera_id = '<%= ENV["CAMERA"] %>';

  CameraTag.observe(cluster_camera_id, 'published', function(){
     $("#new_video").submit();
   });

  CameraTag.observe(cluster_camera_id, 'processed', function(){
     alert('this video has been processed!')
   });

</script>

<style>
  html{
  /* This image will be displayed fullscreen */
  background:url('<%= image_tag(@card.category + ".png") %>') no-repeat center center;

  /* Ensure the html element always takes up the full height of the browser window */
  min-height:100%;

  /* The Magic */
  background-size:cover;
  }

  body{
  /* Workaround for some mobile browsers */
  min-height:100%;
  }


</style>

<section class="card <%=@card.category %>">
  <div class="overlay">
    <div class="frame">
      <div class="container-fluid text-center">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <div class="fb-like" data-href="http://clustercard.net/<%=@card.slug%>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
          </div>
        </div>



        <h1 class="text-center"><%=@card.title %></h1>
        <p class="lead text-center">•••</p>


        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <%= bootstrap_form_for(@video, layout: :inline) do |f| %>
              <%= f.hidden_field :card_id, value: @card.id %>
                <camera 
                id=<%= ENV['CAMERA'] %> 
                name='video' 
                data-app-id=<%= ENV['CAMERA_KEY'] %> 
                data-pre-roll-length='3'
                data-detect-camera='false'
                data-poll-for-processed='true'>
                </camera>
            <% end %>
          </div>
        </div>
        
        <div class="row videos">
          <div class="col-xs-12 text-center">
            <div class="col-lg-12">
              <% @card.videos.each do |v| %>
                <a href="javascript:void(0)" data-toggle="modal" data-target="#video_modal_<%=v.id%>" >
                <%= image_tag(v.small_thumb, class: 'video-message') %></a>
                    <!-- , style: 'border-radius: 50px;' (would round edges on box)-->
                <div class="modal fade" id="video_modal_<%=v.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel"><%=v.contributor%></h4>
                      </div>
                      <div class="modal-body">
                        <video id='vid_<%=v.id%>' data-uuid='<%= v.video_uuid %>'></video><br> 
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>

      <div class="row">
        <div class="col-md-6 col-md-offset-3 text-center">
          <div id="disqus_thread"></div>
          <script type="text/javascript">
              /* * * CONFIGURATION VARIABLES * * */
              var disqus_shortname = 'clustercard';
              
              /* * * DON'T EDIT BELOW THIS LINE * * */
              (function() {
                  var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                  dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
              })();
          </script>
          <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
  $( document ).ready(function() {
    console.log( "ready!" );

    var imageData = Array();

    for(var i = 0; i < imageTemp.2; i++){
        updateImageData( i );
    }

    function updateImageData( i )
        $.ajax({
            type: "HEAD",
            async: true,
            url: "https://cameratag.com/videos/v-3ced23b5-035e-4b8d-9811-dbdc8b383ed6/qvga/small_thumb.png",
            success: function(){
                console.log('yup, it is there');
            }
        });
    }
  });
</script>
</div>

app/views/info/index.html.erb
<div class="jumbotron">
    <center><h1>ClusterCard.net</h1>
    <p><h4>Create a short video in one of the following categories -- then invite others to add short videos of their own -- then send your customized, heart-felt ClusterCard via email or FB: </h4></p>


<div class="col-lg-12">
    <div class="bs-component">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title"><%= "#{Card::CARD_CATEGORIES[0]}" %></h3><%= link_to 'See Example', cardslug_path(Card::CARD_CATEGORIES[0]), class: "btn btn-default btn-sm", method: :get %>
            </div>
            <div class="panel-body">
                Don't send the same ol' FB post!  Send your friends or loved ones a video ClusterCard to wish a very <i>Happy Birthday!</i>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title"><%= "#{Card::CARD_CATEGORIES[1]}" %></h3><%= link_to 'See Example', cardslug_path(Card::CARD_CATEGORIES[1]), class: "btn btn-default btn-sm", method: :get %>
            </div>
        	<div class="panel-body">
            	New family addition?  New graduate?  New job?  Send your 'Congrats' with a video ClusterCard!
        	</div>
    	</div>

    	<div class="panel panel-default">
        	<div class="panel-heading">
            	<h3 class="panel-title"><%= "#{Card::CARD_CATEGORIES[2]}" %></h3><%= link_to 'See Example', cardslug_path(Card::CARD_CATEGORIES[2]), class: "btn btn-default btn-sm", method: :get %>
        	</div>
        	<div class="panel-body">
            	Send some heart-felt wishes for this special occasion.
            </div>
        </div>
    </div>
</div>
<div class="col-lg-12">
    <div class="bs-component">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title"><%= "#{Card::CARD_CATEGORIES[3]}" %></h3><%= link_to 'See Example', cardslug_path(Card::CARD_CATEGORIES[3]), class: "btn btn-default btn-sm", method: :get %>
            </div>
            <div class="panel-body">
                Share the love with anniversary wishes to the deserving couple.
            </div>
        </div>

        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title"><%= "#{Card::CARD_CATEGORIES[4]}" %></h3><%= link_to 'See Example', cardslug_path(Card::CARD_CATEGORIES[3]), class: "btn btn-default btn-sm", method: :get %>
            </div>
            <div class="panel-body">
                Say <i>I'm here for you</i> with a simple, meaningful video message.
            </div>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><%= "#{Card::CARD_CATEGORIES[5]}" %></h3><%= link_to 'See Example', cardslug_path(Card::CARD_CATEGORIES[3]), class: "btn btn-default btn-sm", method: :get %>
            </div>
            <div class="panel-body">
                Your <i>THANK YOU</i> can mean so much more when you say it with a ClusterCard! 
            </div>
        </div>
    </div>
</div>

<h4>Don't see any category matches?  No problem! Send your own fun ClusterCard!</h4>


<br>
<div class="row">
    <div class="col-lg-12">
        <div class="well bs-component">
            <center><legend>Enter a unique web address identifier to start your own:</legend>
                
            <%= bootstrap_form_for(@card, layout: :inline) do |f| %>
                <h3><%= f.label :slug, 'http://clustercard.net/' %>
                <%= f.text_field :slug, hide_label: true, required: true %>
                <%= hidden_field_tag :page1, value = "y" %></p>
                <%= f.submit "Go To Your Card", class: "btn btn-primary btn-block" %></h3></center>
            <% end %>
       
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= favicon_link_tag 'logo.png' %>
  <meta property=og:title content=ClusterCard.net />
  <meta property=og:type content=website />
  <meta property=og:url content=http://clustercard.net />
  <meta property=og:image content=http://i.imgur.com/5fs4BK1.jpg />
  <meta property=og:description content='You are invited to add your personalized video message to my video ClusterCard. Choose birthday, sympathy, congratulations themes, or create your own fun idea.  Ruby/Rails web developer seeking full-time SD-1 position, Spring 2015.' />
  <meta property=fb:app_id content=<%= ENV['FB_APP_ID'] %> />


    <title>ClusterCard</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" src="//normalize-css.googlecode.com/svn/trunk/normalize.css" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
	<link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,900,100italic,300italic' rel='stylesheet' type='text/css'>

	<!-- Optional theme -->
	<!-- <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.2/sandstone/bootstrap.min.css" rel="stylesheet"> -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
	<script src='//cameratag.com/api/v5/js/cameratag.js' type='text/javascript'></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-backstretch/2.0.4/jquery.backstretch.min.js"></script>
	<%= stylesheet_link_tag "application", media: "all" %>
	<%= javascript_include_tag "application" %>

</head>

<body>

	<%= yield %>

</body>
</html>

app/views/pages/slider.html.erb
<script>
  $(function() {
  $(".bs-wizard").bs_wizard();
  });
</script>
<div class="row bs-wizard">  

<div class="col-lg-9">
  <form method="get" action="" accept-charset="UTF-8">
  <fieldset>



    <div class="bs-step inv">
      <div class="bs-step-inner">
        <div class="form-group">
          <label for="field_1">Field 1</label> 
          <input type="text" class="form-control" value="" name="field_1" id="field_1" autofocus="autofocus">
        </div>

        <div class="form-group">
          <label for="field_2">Field 2</label> 
          <input type="text" class="form-control" value="" size="30" name="field_2" id="field_2">
        </div>
      </div>
    </div>




    <div class="bs-step inv">
      <legend>Second Step</legend>
      <div class="bs-step-inner">
        <div class="form-group">
          <label for="field_3">Field 3</label> 
          <input type="text" class="form-control" value="" size="30" name="field_3" id="field_3">
        </div>

        <div class="form-group">
          <label for="field_4">Field 4</label> 
          <input type="text" class="form-control" value="" size="30" name="field_4" id="field_4">
        </div>
      </div>
    </div>

    <div class="bs-step inv">
      <legend>Third Step</legend>
      <div class="bs-step-inner">
        <div class="form-group">
          <label for="field_5">Field 5</label> 
          <input type="text" class="form-control" value="" size="30" name="field_5" id="field_5">
        </div>

        <div class="form-group">
          <label for="field_6">Field 6</label> 
          <input type="text" class="form-control" value="" size="30" name="field_6" id="field_6">
        </div>

        <button class="btn btn-default" type="reset" id="last-back">Go Back</button>
        <input class="btn btn-success submit-btn" type="submit" value="Submit" />
      </div>
    </div>
  </fieldset>
  </form> 
</div>
</div>

app/views/videos/show.html.erb
<h3>Here is the video you submitted for the card</h3>

<h4>Clustercard.net/<%= @video.card.slug %></h4>
<video id='vid_<%=@video.id%>' data-uuid='<%= @video.video_uuid %>'></video>

<%= button_to "Delete this video", video_path(:id => @video.auth_token), :method => :delete, :class => 'btn btn-large btn-warning', data: { confirm: 'Are you sure?'} %>